# 1. Редирект с домена без WWW на домен с WWW
server {
    listen 80;
    server_name dymsystems.pp.ua;

    return 301 http://www.dymsystems.pp.ua$request_uri;
}

# 2. Основной сервер для WWW-версии
server {
    listen 80;
    server_name www.dymsystems.pp.ua localhost;

    root /var/www/public;
    index index.php index.html;

    # Обрезка слэша на конце, если он есть (опционально, для чистоты URL)
    # rewrite ^/(.*)/$ /$1 permanent;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}